//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace merge_gui.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("merge_gui.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   VMD file (*.vmd)|*.vmd に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string filter_vmd_file {
            get {
                return ResourceManager.GetString("filter_vmd_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string msg_error_exit {
            get {
                return ResourceManager.GetString("msg_error_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Finished に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string msg_finished {
            get {
                return ResourceManager.GetString("msg_finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output VMD file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string title_output_file {
            get {
                return ResourceManager.GetString("title_output_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select body motion file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string title_select_body_file {
            get {
                return ResourceManager.GetString("title_select_body_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select face motion file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string title_select_face_file {
            get {
                return ResourceManager.GetString("title_select_face_file", resourceCulture);
            }
        }
    }
}
